### ISSUE TITLE
Can't complete registration at https://bugs.ruby-lang.org/login

### ISSUE THREAD

**Issue by BurdetteLamar** [ruby/b.r-l.o#100]
Says "Account was successfully created. An email containing the instructions to activate your account was sent to burdettelamar@yahoo.com."

No email.  Tried "You haven't activated your account yet. If you want to receive a new activation email, please click this link." Many times.  Still no email.

Thanks for any help.

Burdette

**Comment by hsbt** [comment]
I couldn't reproduce it. I could singup my another mail address.

Can you confirm the spam folder or others?

**Comment by ahorek** [comment]
It works for me as well
