### ISSUE TITLE
not receiving email notifications for watched issues

### ISSUE THREAD

**Issue by bughit** [ruby/b.r-l.o#101]
I have a gmail address on the bugs.ruby-lang.org account that's active and working. I am not receiving notifications (they are not in spam)

**Comment by bughit** [comment]
@hsbt I receive email change notifications when I change the email to username+something@gmail.com (which goes to the same mailbox as username@gmail.com)  But not watched issue notifications.

Who is administering bugs.ruby-lang.org? Can the look into this?

**Comment by ahorek** [comment]
I tested the code from this repository and it seems to be ok, notifications were sent. I expect there's something wrong on the server. Could someone check logs?

**Comment by hsbt** [comment]
> Who is administering bugs.ruby-lang.org?

It's me. But I have no enough time to investigate it. Because my OSS time is completely volunteer.

**Comment by bughit** [comment]
@hsbt 

I just performed the following test to understand the scope of this.

- signed up with a new email
- received activation email
- activated the account and watched issue 16148
- posted a message to 16148 from my original account and the new one (both are configured for notification of own changes)
- neither the old nor the new account received a notification of either post

So this does not appear to be a narrow problem. A bug tracker that does not notify is useless, you might as well switch to github issues.

**Comment by hanachin** [comment]
`redmine_bugs_ruby_lang` plugin overrides Redmine's notification, notifications are sent to mailing lists.

> ## mailing_list_integration
>
> This plugin integrates mailing lists with Redmine.
>
> * Transports issue_add, issue_edit mails to the correct mailing list.
>* Adds a hyperlink to the corresponding message into issue page
https://github.com/ruby/b.r-l.o/tree/ro-4-1/plugins/redmine_bugs_ruby_lang

https://github.com/ruby/b.r-l.o/blob/235586ed6bebc56ef9cf9b5a5d5f1699e1decdad/plugins/redmine_bugs_ruby_lang/lib/redmine_mailing_list_integration/redmine_ext/mailer.rb#L3-L26

**Comment by bughit** [comment]
@hanachin @hsbt 

I am not on the mailing list. There's no indication when signing up to bugs.ruby-lang.org that you have to be, in fact you may not even know it exists.

You are basically telling bug reporters and users to go away, we don't want your input, because they will not be participating in any discussions if they're not getting notifications.

I have never seen an open source project with a bug tracker this broken.

**Comment by bughit** [comment]
@matz Is it intentional that the ruby bug tracker only sends email notifications of issue updates to the mailing list, thereby excluding anyone not on the mailing list from bug and feature discussion?

**Comment by matz** [comment]
It's not intentional. If Redmine has the option to notify the users, I'd like to turn it on.

**Comment by matz** [comment]
At the same time, I don't want to be flooded by notification emails.

**Comment by hsbt** [comment]
I think this override is not intentional. We should change `update` to `add`.

I'll merge it if anyone send the patch to me.

**Comment by ahorek** [comment]
sent a PR

**Comment by larskanis** [comment]
I'm also affected by this bug. I don't have the time to follow the mailing list, so I have to poll each interesting issue for updates, which is tedious and I often fail to answer in a timely manner.

**Comment by bughit** [comment]
@hsbt 

What happened to

> I'll merge it if anyone send the patch to me.

The PR (#115) has been gathering dust for months. Is there's something wrong with it?

**Comment by hsbt** [comment]
I'm bit of aware with the current code of #115 . Because It's too complex to resolve to this issue.

**Comment by ahorek** [comment]
> It's not intentional. If Redmine has the option to notify the users, I'd like to turn it on.

it's clearly a bug in the mailing_list_integration modification that should be fixed.

> At the same time, I don't want to be flooded by notification emails.

Redmine notifications can be easily disabled on a user's profile = no problem.

> I'm bit of aware with the current code of #115 . Because It's too complex to resolve to this issue.

So, do you have a less complex proposal that restores the original notifications functionality without breaking your modifications for mailing lists? Both of them should work independently, right? Feel free to tell us what to do next.

I know you're busy, but there doesn't seem to be any interest in fixing this. Nothing is really changed since opening this issue more than a year ago :-(

**Comment by hsbt** [comment]
I won't to maintain the complex code. After merging this, I have a responsibility to maintain this change.

**Comment by ahorek** [comment]
the best way would be to add a test case to ensure it works as expected and eases the maintenance costs.

but fixing existing Redmine tests on the b.r.l.o's fork would be a much more complex challenge you probably won't be willing to review.

unless you have your own idea, a suggestion on how to fix it differently, or another maintainer willing to test and maintain the change, I think we're out of options and there's no resolution for this.

**Comment by bughit** [comment]
@hsbt 

You were asked "do you have a less complex proposal that restores the original notifications functionality"?

But you just repeated that it's complex "I won't to maintain the complex code"

Please answer the question you were asked, what is the proper "simple" way to fix this?

**Comment by ahorek** [comment]
an alternative approach https://github.com/ruby/b.r-l.o/pull/118 is thanks to @jonathanhefner simpler. Is it acceptable now?

**Comment by dentarg** [comment]
@larskanis As a workaround for this problem, I've been using the "Atom" link (found at the bottom of the issue page) to follow bugs, a bit tedious to set up (especially if you aren't already using an RSS Reader/service), but gets you out of the manual polling at least

**Comment by Inversion-des** [comment]
**Please fix the email notifications** for watched issues. 
It's a pain to manually visit bookmarked pages or track them via RSS. 😭

**Comment by bughit** [comment]
@hsbt Is there a problem with #118?

**Comment by bughit** [comment]
Now all email is going to spam (see #177)
