### ISSUE TITLE
Forgot password doesn't work

### ISSUE THREAD

**Issue by asterite** [ruby/b.r-l.o#104]
Steps to reproduce:
- Go to https://bugs.ruby-lang.org/account/lost_password
- Put email
- Receive confirmation email
- Choose a password and retype

The website will go to the login form. There you put your email and the password you chose and it doesn't work.

From that point I lost access to my account.

**Comment by wyhaines** [comment]
Likewise.  I changed my password, and now I can not get into my account. I would really like to get into my account again.

**Comment by hsbt** [comment]
I investigate this issue. Our server that is heroku environemnt sent password recovery mail correctly, but I didn't confirm to receive it. I'm not sure why this feature is not working now. 

I totally wonder why issue notification is working fine, but only password recovery is not working.

**Comment by hsbt** [comment]
Unfortunately, I couldn't repro this.
