### ISSUE TITLE
URI.parse fails to parse correctly URN or other special characters in path/url

### ISSUE THREAD

**Issue by poloka** [ruby/b.r-l.o#117]
URI.parse looks to fail parsing endpoints that have special characters.  For example:
```
url = 'http://foobar.com/#/applications/'
path = 'my_application'
URI.join(url, path).to_s
```
The result renders `http://foobar.com/my_application`.

Or in the case of executing an API marked by URNs so the ID field in my `GET` request is something like
```
key = 'urn:api:baz:1'
url = 'http://foobar.com/api'
URI.join(url, key).to_s
```
The result renders `urn:api:baz:1`

**Comment by hsbt** [comment]
Can you file it to https://bugs.ruby-lang.org/ ?

This repository is the wrong place to report ruby issues.

**Comment by poloka** [comment]
thanks @hsbt , i've logged https://bugs.ruby-lang.org/issues/17293 for the issue.
