### ISSUE TITLE
"The administrator requires you to enable two-factor authentication." - 2FA

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/b.r-l.o#123]
Hey folks,

Perhaps 2 days ago I suddenly need to use 2FA if I am to use the official bug tracker.

I get redirected onto:

https://bugs.ruby-lang.org/my/twofa/totp/activate/confirm

"The administrator requires you to enable two-factor authentication."

I have no smartphone (this may sound strange but it is true). Even if I were to have one
this is hugely problematic. For example, Google Authenticator - there is no way I can
depend on Google for anything I do. I still use gmail, because I am lazy, but if I were to
"start from scratch today" I would not depend on Google anymore. Anyway, to me
the 2FA effectively locks me out of the ruby bug tracker. Perhaps there are very valid
use cases why that was done, but to me it means that I can no longer discuss at the
bug tracker. This, in turn would mean that I would become a second class citizen to
ruby (since I can not really report problems; and I don't really use emails. I am
notoriously bad with emails, always have been in the last +20 years).

I am fine with changing my password for the bug tracker if that is necessary; I did
so at rubygems.org too. Perhaps the 2FA is due to compromised passwords? I
can change it fine, but right now I can not do anything at the official ruby bug
tracker because the 2FA wall always shows up.

For example if I want to go at "My Account", I get blocked by the 2FA showing up
and showing: "The administrator requires you to enable two-factor authentication." 

What this then means is that I can no longer use the bug tracker. But I honestly
do not want to be forced to have to use 2FA ... I don't think it was mandatory
when we used to sign up for the bug tracker? Is it 100% certain that this will
permanently stay the way it is now? Are there no alternatives to this?

I had this discussion before at rubygems.org, but mandatory 2FA would mean
that my account at rubygems.org would be not useable anymore, so there
is no point in publishing gems for me at rubygems.org, whereas on github
I could do so just fine with 2FA. So this is a head-scratcher to me ... I assume
for smartphone users this is no big deal, but for me it's effecting my retirement
from ruby. The reason is that I would be a second class citizen in this regard
when it comes to reporting bugs (since I can no longer use the official
bug tracker). Since I don't want to be penalized like this, I would not continue
to use ruby, and would instead opt to switch to other languages.

I am not making any fast decisions here; and it's fine if this issue can not
be instantly resolved, I understand this. So perhaps in a month or two
there may be some change or something.

As said I am fine with changing password or using my gmail account
and stuff, if that is necessary. But mandatory 2FA means I am effectively
retired from ruby, so hopefully that issue comment has some effect 
before I'll throw in the towel. (I have not yet decided whether to then
keep my account at github, but the main reason for using it was due
to ruby actually, and being able to provide feedback - the feedback
and issue tracker of github is GREAT. Gitlab is so much more annoying;
python trac even worse; sourceforge a disaster...)

Anyway, hopefully this can at the least notify of some problems, so there
may be some resolution where 2FA does not become mandatory. And
if not, well then I did something before throwing in the towel in regards
to ruby after almost 20 years... but hopefully it at the least shows a
potential problem. By the way, I can comment on github fine without
2FA, so this is REALLY strange if you think about it ....

**Comment by hsbt** [comment]
> Are there no alternatives to this?

I don't know how to protect your account and our tracker from the spammer, cracker and etc today.

> I have no smartphone (this may sound strange but it is true).

You can use MFA without smartphone or other mobile devices.

See http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/103415 or http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/103416.
