### ISSUE TITLE
Send out mail with full name of commenter

### ISSUE THREAD

**Issue by duerst** [ruby/b.r-l.o#138]
I have recently noticed that the mail from bugs.ruby-lang.org sometimes drops the name of the commenter.

As an example, in [ruby-core:104983] [Ruby master Feature#12075] some container#nonempty?,
it says only "duerst", without mentioning my full name.
On the other hand, e.g. for
[ruby-core:104928] [Ruby master Bug#18077] Marshal.dump(closed_io) raises IOError instead of TypeError,
it has "nobu (Nobuyoshi Nakada)".

A change seems to have happened just before [ruby-core:104925].
Before, the from field was
From: nobu@ruby-lang.org
but afterwards, it is
From: nobu (Nobuyoshi Nakada) <noreply@ruby-lang.org>
Changing to a 'noreply' address makes sense, but why is the full name dropped for some people?

In the small sample available up to now, the only person without full name is me. That points to two possibilities for this phenomenon: 1) Something in my setting on bugs.ruby-lang.org is wrong (but it has my first name and last name). 2) the "ü" character in my last name somehow triggers exceptional processing (which it should't).

**Comment by hsbt** [comment]
I got the detail of this from @duerst . But I didn't investigate yet.

**Comment by duerst** [comment]
The 'ü' in my name may be the reason for the problems. But it shouldn't be a problem. Redmine uses Ruby on Rails, which can handle Unicode very well.

**Comment by hsbt** [comment]
It seems Redmine problem, not our deployment.

**Comment by duerst** [comment]
Reported to Redmine bug tracker at https://www.redmine.org/issues/38223.
