### ISSUE TITLE
Rvm 2.5.1

### ISSUE THREAD

**Issue by mayankmishra1995** [ruby/b.r-l.o#142]
closure.c:264:14: error: implicit declaration of function 'ffi_prep_closure' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    result = ffi_prep_closure(pcl, cif, callback, (void *)self);

Ruby ffi issue 1.19.18
Fetching ffi 1.9.18
Installing ffi 1.9.18 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/mayankmishra/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ffi-1.9.18/ext/ffi_c
/Users/mayankmishra/.rbenv/versions/2.5.1/bin/ruby -r ./siteconf20210913-21169-au64g6.rb extconf.rb --with-cflags=-Wno-error=implicit-function-declaration
checking for ffi_call() in -lffi... yes
checking for ffi_prep_closure()... no
checking for ffi_raw_call()... yes
checking for ffi_prep_raw_closure()... yes
checking for shlwapi.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
checking for ffi_prep_cif_var()... yes
creating extconf.h
creating Makefile

Permission denied @ rb_file_s_rename - (mkmf.log,
/Users/mayankmishra/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/-darwin-20/2.5.0/ffi-1.9.18/mkmf.log)

Gem files will remain installed in /Users/mayankmishra/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ffi-1.9.18 for inspection.
Results logged to /Users/mayankmishra/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/-darwin-20/2.5.0/ffi-1.9.18/gem_make.out

An error occurred while installing ffi (1.9.18), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.18' --source 'https://rubygems.org/'` succeeds before bundling.

**Comment by hsbt** [comment]
@mayankmishra1995 You should file it to https://github.com/ffi/ffi or https://github.com/rvm/rvm .
