### ISSUE TITLE
pod install not working

### ISSUE THREAD

**Issue by SazzDS** [ruby/b.r-l.o#144]
I was trying to use react-native-cli but it cant install cocoapods dependencies.

  
641 /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/digest/sha2.rb
  642 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle
  643 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/platform.rb
  644 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/data_converter.rb
  645 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/types.rb
  646 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/library.rb
  647 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/errno.rb
  648 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/abstract_memory.rb
  649 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/pointer.rb
  650 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/memorypointer.rb
  651 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/struct_layout.rb
  652 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/struct_layout_builder.rb
  653 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/struct_by_reference.rb
  654 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/struct.rb
  655 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/union.rb
  656 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/managedstruct.rb
  657 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/callback.rb
  658 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/io.rb
  659 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/autopointer.rb
  660 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/variadic.rb
  661 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/enum.rb
  662 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/version.rb
  663 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi/ffi.rb664 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: https://www.ruby-lang.org/bugreport.html

[IMPORTANT]
Don't forget to include the Crash Report log file under
DiagnosticReports directory in bug reports.

zsh: abort      pod install

**Comment by hsbt** [comment]
@SazzDS You should report this to https://github.com/CocoaPods/CocoaPods. This tracker only handles the tracker's issue, not language, library, toolchains.
