### ISSUE TITLE
Apple M1 bug on installing Cocoapod

### ISSUE THREAD

**Issue by toseefkhilji** [ruby/b.r-l.o#147]
[BUG] Bus Error at 0x0000000102f14000
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
![Screenshot 2022-02-21 at 10 44 11 AM](https://user-images.githubusercontent.com/2367614/154893689-13463f8e-5f89-4c32-96a5-7b4721e4bcbf.png)
[ruby-2022-02-21-104237.ips.zip](https://github.com/ruby/b.r-l.o/files/8106419/ruby-2022-02-21-104237.ips.zip)

**Comment by hsbt** [comment]
see https://github.com/ruby/b.r-l.o/issues/146#issuecomment-1029463193
