### ISSUE TITLE
trying to install a pod to my xcode project and encountered a crash and abort

### ISSUE THREAD

**Issue by yaya212** [ruby/b.r-l.o#149]
steps I have taken:
1. installed cocoapod
2. initiated a pod to my project
3. formatted the podfile adding the pod as follows: pod 'CLTypingLabel' between the comment and the "end" keyword
4. hitting the install pod command

**Comment by hsbt** [comment]
see https://github.com/ruby/b.r-l.o/issues/146#issuecomment-1029463193
