### ISSUE TITLE
Cocoapods - pod install ruby error

### ISSUE THREAD

**Issue by nick1289** [ruby/b.r-l.o#151]
Trying to link Firebase to a swiftui project via CocoaPods

To date I did 'pod init' which worked well but when it came time to 'pod install' I got this error:

________________________________________________________________________

635 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi/version.rb
636 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi/ffi.rb
637 /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: https://www.ruby-lang.org/bugreport.html

[IMPORTANT]
Don't forget to include the Crash Report log file under
DiagnosticReports directory in bug reports.

zsh: abort      pod install
________________________________________________________________________

Any help?
*note I modified the Podfile to add 'Firebase/Firestore' *

**Comment by hsbt** [comment]
see https://github.com/ruby/b.r-l.o/issues/146#issuecomment-1029463193
