### ISSUE TITLE
Poor English (in, 'If you have issue of this tracking system, Please create issue to' and elsewhere)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [ruby/b.r-l.o#152]
[This page](https://bugs.ruby-lang.org/) has:

> If you have issue of this tracking system, Please create issue to

That should be:

> If you have a problem with this tracking system itself, then please open an issue at

Somewhat similarly, in the code snippet [here](https://www.ruby-lang.org/en/), 'Code' should not have its first letter capitalised.

**Comment by hsbt** [comment]
Fixed. Thanks.
