### ISSUE TITLE
How to start Ruby?

### ISSUE THREAD

**Issue by IvanZez** [ruby/b.r-l.o#157]
Good afternoon! I installed Ruby on Fedora without problems, but I can't find Ruby or open it. When I try to type "irb" and press Enter, I get an error: bash: irb: command not found...
Similar command is: 'erb' .
Please help me get Ruby up and running!

**Comment by hsbt** [comment]
@IvanZez Unfortunately, this repo is not FAQ place. You should ask https://stackoverflow.com/.

**Comment by IvanZez** [comment]
Okay, thanks for the reply!
