### ISSUE TITLE
Enabling 2FA fails: Code is invalid or outdated

### ISSUE THREAD

**Issue by kyonides** [ruby/b.r-l.o#163]
I've tried many times to pass the double factor authentication to be able to file a bug report on bugs.ruby-long.org to no avail.
My password works fine but not so the 2FA. No matter how many times I enter the code offered by Google Authenticator on the field, it simply fails. I have also rescanned the code to match the one presently displayed on screen, only to get the same result: a failure to pass the test. I am just stuck there...

**Comment by hsbt** [comment]
I checked your status. I confirm you still register 2FA code in our tracker.

I have no idea to resolve it because I and other people did register 2FA code fine.

**Comment by kyonides** [comment]
Fine. Then I won't submit the Dir#entries and Dir#glob bug reports for I
can't even pass the 2FA process. You know, you could do it on my behalf
unless nobody cares about that.

**Comment by hsbt** [comment]
@kyonides https://bugs.ruby-lang.org/issues/19086 seems your post. Thanks for your effort.

**Comment by kyonides** [comment]
Completed? Not really. Every so often it fails to accept the code I have to
enter, and it took me several attempts to reach the account settings page.
If I went back to a previous page, it would still ask for the 2FA code. :(

**Comment by hsbt** [comment]
There is no plan to the next action by me because I never faced this issue. 

Can you provide the repro case for this? I'll re-open and investigate this again.

**Comment by hsbt** [comment]
@kyonides I got this issue from another people. I disabled MFA mandatory on bugs.ruby-lang.org now until fixing this issue on our tracker.
