### ISSUE TITLE
2FA prompt, but I never set up 2FA

### ISSUE THREAD

**Issue by mttkay** [ruby/b.r-l.o#164]
I've been locked out of my account because every time I try to log in, I get a 2FA challenge, but I never set up 2FA so I have no way to provide any 2FA codes.

I can reset my password (just did), but that does not help; I'm still being prompted to enter an OTP to log in.

Could someone temporarily disable 2FA on my account so that I can log in and actually set it up myself?

**Comment by hsbt** [comment]
What's your email address or account name?

**Comment by mttkay** [comment]
Username is `mk`, thanks!

**Comment by hsbt** [comment]
@mttkay I removed your MFA configuration. Can you try again?

**Comment by mttkay** [comment]
Perfect, it works. Thank you! :bow:
