### ISSUE TITLE
Provide instructions for 2FA reset

### ISSUE THREAD

**Issue by djberg96** [ruby/b.r-l.o#165]
I had a situation where the phone I was using for 2FA for bugs.ruby-lang.org died on me.

When I went to visit to bugs.ruby-lang.org there was no obvious way to reset it. I couldn't log in without 2FA, and couldn't get a new QR code without logging in.

I have the backup codes, but am not sure how they can be used currently.

Please add instructions for people who run into this situation so they know what to do.

**Comment by hsbt** [comment]
It's redmine's issue, not our tracker especially.

Isn't https://bugs.ruby-lang.org/#Contact enough? I will add the instruction to bugs.ruby-lang.org for resetting MFA device when you provide it.

**Comment by rubyFeedback** [comment]
Could we make the bug tracker more flexible? I mean it should be highly unlikely that old users are bots, but all are handicapped by the 2FA. I can report bugs on github, but no longer on the ruby tracker.

**Comment by hsbt** [comment]
@rubyFeedback I welcome your patch for avoiding new bot user on our ruby tracker.

**Comment by hsbt** [comment]
And you didn't know. The current configuration of 2FA is NOT mandatory on the ruby tracker. Please try login it.
