### ISSUE TITLE
[Bug] Too long case/when menu leads to SYNTAX_SUGGEST_TIMEOUT error

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/b.r-l.o#173]
Too long case/when menu lead to:

    foobar.rb: Search timed out SYNTAX_SUGGEST_TIMEOUT=1, run with DEBUG=1 for more     info/usr/lib/ruby/3.2.0/ripper/core.rb:36:in `_dispatch_2'
    <internal:kernel>:90:in `parse'
    <internal:kernel>:90:in `tap'foobar.rb:14990: nesting too deep (SyntaxError)
             /^statistik_?übungen/i
              ^~~~~~~~~~~~~~~~~~~~

This case when menu has +15.000 lines (including comments though).

When I remove the last entry, it works. But when I add that entry, the above 
error shows up. There seems to be some hard cap.

PS: I can not report bugs on the ruby tracker anymore because it mandates
2FA now which I don't have.

**Comment by rubyFeedback** [comment]
Hmm. I don't see an option to upload a file to test it.

**Comment by hsbt** [comment]
This tracker is not language tracker.
