### ISSUE TITLE
Any way two "forgot" the two factor code?

### ISSUE THREAD

**Issue by jpalermo** [ruby/b.r-l.o#174]
We have a team account we made last year and nobody remembers adding 2FA to the account, but it seems to be enabled.

We were able to reset the password via email reset (which was our main goal since the username/password was stored in LastPass).

But we're not able to sign into the account with the 2FA.

Thanks!

**Comment by hsbt** [comment]
@jpalermo Can you share your account name of bugs.ruby-lang.org? I will disable MFA configuration for your account.

**Comment by jpalermo** [comment]
Yeah, username is `bosh-ecosystem-vmware`

Thanks!

**Comment by hsbt** [comment]
@jpalermo I disabled now. Please check your account.

**Comment by jpalermo** [comment]
Got it, rotated passwords and reenabled (and recorded) the MFA.

Thanks again!

**Comment by hsbt** [comment]
Your welcome ❤️
