### ISSUE TITLE
Email integration is not working after migrating mailmanlists

### ISSUE THREAD

**Issue by hsbt** [ruby/b.r-l.o#175]
https://bugs.ruby-lang.org/issues/19276

**Comment by hanazuki** [comment]
I have the following observations.

Email messages from b.r-l.o Redmine through ruby-core list currenlty have these header fields:
```
To: ruby-core@ml.ruby-lang.org
Reply-To: Ruby developers <ruby-core@ml.ruby-lang.org>
From: "hsbt (Hiroshi SHIBATA) via ruby-core" <ruby-core@ml.ruby-lang.org>
Cc: "hsbt (Hiroshi SHIBATA)" <noreply@ruby-lang.org>
```

Therefore when the list's subscriber hits the Reply All button on their mailer, it sends a message to these mailboxes:
```
To: Ruby developers <ruby-core@ml.ruby-lang.org>
Cc: "hsbt (Hiroshi SHIBATA)" <noreply@ruby-lang.org>
```

This results in a bounce message that indicates `noreply@ruby-lang.org` does not exist.

I suppose we need to set the correct email address to Cc: or completely remove it.

**Comment by hsbt** [comment]
@hanazuki Thanks for your investigation. 

This `Cc` header is added by mailmanlists for DMARC mitigation. mailmanlists replaced `from` header with mailing-list address and reuse `from` address to `Cc` header.

I replaced `from` header at bugs.ruby-lang.org for mitigating DMARC. We may remove bounced `Cc` header now.
