### ISSUE TITLE
Need to change username

### ISSUE THREAD

**Issue by hibachrach** [ruby/b.r-l.o#186]
Hello, is it possible to change my username? I've changed my real-life name and the username reflects my old real-life name.

**Comment by hsbt** [comment]
@hibachrach Sorry to late response. I can change your nickname. Can you provide old and new nickname for bugs.ruby-lang.org?

**Comment by hibachrach** [comment]
Sure:
* Old name: [Redacted]
* New name: `hibachrach`

Thank you!

**Comment by hsbt** [comment]
@hibachrach 👋 Thanks for providing that. I update your login name. Can you confirm that?

**Comment by hibachrach** [comment]
Yes, it looks good. Thank you!
