### ISSUE TITLE
Can't login due to two-factor authentication

### ISSUE THREAD

**Issue by hadmut** [ruby/b.r-l.o#187]
Hi, 
I wanted to report a feature request to https://bugs.ruby-lang.org/

I do have an account there, since I had reported bugs ages ago. I did not have the password anymore (at least not on the machine I am using quite now), and activated the procedure to reset the password, which worked well. Could set a new password. 

But then, when trying to login, it first asks for username and password, and then 

> Two-factor authentication
> 
> Please enter your two-factor authentication code.

Neither can I recall to ever have set 2FA for bugs.ruby-lang.org, nor would I have one or even recognize, which sort of 2FA is expected. There is several methods. 

Nevertheless, I do not have a 2FA for this web page, and there is no obvious way to reset the 2FA. 

So how would I ever be able to login again? Or is my account burned for all eternity?

regards

**Comment by hsbt** [comment]
@hadmut Can you share your account name or email address? I will reset your 2FA configuration.

**Comment by hadmut** [comment]
My account name is hadmut

My email address is the same 
@danisch.de

**Comment by hsbt** [comment]
Thanks. I reset your 2FA configuration now. Can you try to login again?

**Comment by hadmut** [comment]
It worked. Thank you.
