### ISSUE TITLE
`Could not locate Gemfile` reported during installation

### ISSUE THREAD

**Issue by Ricky-Tigg** [ruby/b.r-l.o#188]
**Component** (from a Fedora's repository): rubygem-bundler v. 2.5.3.

Hello. Reported in red text **at the end** of the installation process of the component: `Could not locate Gemfile`.

From this message I can deduce that a _Gemfile_ file must be located. However, unknown are for what purpose such a file is to be located and the methodology to acquire it.

**Comment by hsbt** [comment]
This repository is NOT for usage of Ruby. Please file it to https://github.com/rubygems/rubygems/ or https://bugs.ruby-lang.org/
