### ISSUE TITLE
Missing 2FA information, login impossible

### ISSUE THREAD

**Issue by gsteemso** [ruby/b.r-l.o#190]
I submitted a bug to the Ruby developers last week, which involved getting an account on their bug tracker.  I now can't follow up on it, because when I try to log in it asks me for a two-factor authentication passcode that I never receive.  There's no button to resend it, and I'm not certain whether it even asked me what to set up when I opened the account in the first place!

Then, when I come here to say that the non-working thing doesn't work, it says READ THE GUIDELINES BEFORE CONTRIBUTING... with a link to an empty document.  If there aren't any guidelines, nothing wrong with that, but maybe leave a note saying so?

**Comment by hsbt** [comment]
I reset your 2FA configuration now.

**Comment by gsteemso** [comment]
Thank you, good sir!This is an enormous load off of my mind.On Jul 25, 2024, at 7:00 PM, Hiroshi SHIBATA ***@***.***> wrote:﻿
I reset your 2FA configuration now.
