### ISSUE TITLE
ruby-dev/ruby-core 誤爆警告機能

### ISSUE THREAD

**Issue by nurse** [ruby/b.r-l.o#34]
日本語で書いた Issue を ruby-core に送ってしまったり、英語で書いた Issue を ruby-dev に送ってしまう不幸な事故が絶えないので、本文に non ASCII が含まれているか否かで確認ダイアログなりを出して欲しい

**Comment by hsbt** [comment]
最近は英語のみとなってきていて起きてないので様子見にしときます。
