### ISSUE TITLE
Password requirements / lost password issue

### ISSUE THREAD

**Issue by hannesfostie** [ruby/b.r-l.o#36]
I just tried to register on Redmine but it completely failed to let me in.
- Register using 1password and a new password of a good 20 characters including { and +
- Receive activation mail, click link, see message saying my account was activated
- Attempt log in, doesn't work
- Use lost password functionality, first 20 characters without anything special, then 14 characters

End result: still not getting in :-)

**Comment by hsbt** [comment]
This issue is over 10+ years old. If you need to my action, please let me know about that.
