### ISSUE TITLE
担当者フィルタが動いてない

### ISSUE THREAD

**Issue by hsbt** [ruby/b.r-l.o#78]
@akr さんから報告、押しても何も出ない

**Comment by komagata** [comment]
@hsbt こちら、チケットのフィルターの担当者についてでしょうか？
現状ですと動いているように見えます。

<img width="1226" alt="スクリーンショット 2021-03-26 10 48 07" src="https://user-images.githubusercontent.com/16577/112565706-e5c62d80-8e20-11eb-9977-b25746fcaa53.png">

**Comment by hsbt** [comment]
👍  いつの間にか直っていたようですね。ありがとうございます。
