### ISSUE TITLE
Captchas?

### ISSUE THREAD

**Issue by Shalmezad** [ruby/b.r-l.o#92]
Given the semi-regular occurrence of spam in the bug tracker, has any though been given into adding a captcha such as the one located here?
http://www.redmine.org/plugins/recaptcha

**Comment by nurse** [comment]
As far as I understand, such spams are issued by hand.
(because there's email authentication on signing in before creating ticket)
Therefore captcha won't work.

Anyway spam is annoying issue.
We are trying [sqreen](https://docs.sqreen.io/sqreen-for-ruby/ruby-agent-users-monitoring/) now.
