### ISSUE TITLE
Uh Oh! Sqreen has detected an attack

### ISSUE THREAD

**Issue by 0leynikov** [ruby/b.r-l.o#95]
Sqreen makes bugs.ruby-lang.org barely usable.

When I log in using Tor Browser, I start receiving 403 status code and "Uh Oh! Sqreen has detected an attack" response on all requests. It happens every time. That's annoying. I can't even read the tracker for that interval.
Then I open another browser, but now I can't even log in anymore: 403 with the same message.

I have to wait for at least an hour after that to be able to use the system.
Could you please do something with it?

**Comment by 0leynikov** [comment]
It is probably related to Tor.
When I use Firefox without proxies from the start, the above problem doesn't occur. But I'd like to use Tor Browser to access the tracker.

**Comment by nurse** [comment]
Recently we have many spams through tor, and after blocking tor and some other defences, spams are decreased now. We apologies for your trouble and understand your privacy. But we cannot allow Tor browser at this condition. We are sorry about that but appreciate for your understanding.

**Comment by 0leynikov** [comment]
Thanks for your answer.

I'm afraid, it might prevent some people from contributing to Ruby. You've just logged in, and you already treated like a spammer, because you happened to use Tor. Although it helps to fight spam, it also gets in the way of innocent users. Do you think it worth such false positives?

In #92 you said that spammers are probably doing their thing manually, since there is an email confirmation after registration. But have you tried adding captchas?
Email confirmation isn't something that cannot be automated, so probably captchas for suspicious users could have helped. But of course, I don't have data to judge if they do it manually or not, you know better.

Still, maybe other solutions worth a try? How about not allowing new users to create issues and add comments for some period of time after registration? Maybe implement some heuristic checks for spam to check issues before publishing?

It seems like Sqreen in it's current configuration will temporarily block even some well-known user if they login over Tor. Maybe this could be changed to only suspect new users being spammers? And after the user posted the first couple of comments or issues, add them in the whitelist of known users.

A combination of these and other techniques could probably stop spam as efficient as the current setup, but will also be easier on Tor users. What do you think?
I understand that you have limited resources, but maybe I can help?

**Comment by hsbt** [comment]
We are preventing to access used Tor by sqreen for protecting against malicious attacks, not only spammers.

**Comment by 0leynikov** [comment]
I don't have experience with Sqreen, so could you please tell me is it possible to continue using their service to prevent spam and attacks, but at the same time make bugs.ruby-lang.org more usable over Tor? Maybe it can be configured not to block users for an hour  just for signing in?

**Comment by hsbt** [comment]
> the same time make bugs.ruby-lang.org more usable over Tor?

Unfortunately, we prevent to use our tracker via Tor. Can you try again without Tor?

**Comment by 0leynikov** [comment]
Yeah, it works OK without Tor, as I mentioned [above](https://github.com/ruby/b.r-l.o/issues/95#issuecomment-445164248).
This discussion isn't going anywhere, you just repeat that on b.r-l.o Tor is blocked. You don't seem to consider my point. Okay, sorry for bothering you, feel free to close the issue.

**Comment by esparta** [comment]
I got the same issue by using Tor.
Tried with other browsers, and all of them got my the same problem when trying to login (not for browsing). Looks like my account is locked. Is there a way to unlock. My login name is `esparta`, the same as my github account.

**Comment by esparta** [comment]
Just an update. Today I tried to login using Firefox, and no problems at all.
Not sure if was only a temporal block or admin needs to do something :)
