### ISSUE TITLE
mailing list tags

### ISSUE THREAD

**Issue by ahorek** [ruby/b.r-l.o#96]
are these links supposed to be here? the formatting looks odd

![obrazek](https://user-images.githubusercontent.com/9540855/51080891-d3e68d00-16e3-11e9-9693-b6d3af2bc268.png)

@hsbt thanks for upgrading ruby-lang to redmine 4.0 👍 
https://bugs.ruby-lang.org/issues/15530

**Comment by hsbt** [comment]
@ahorek Thanks for your report. It seems to simple migration bug.

**Comment by hsbt** [comment]
I fixed at https://github.com/ruby/b.r-l.o/commit/0c5497be4429819321254e04cd30ce62ef59dbfd
