### ISSUE TITLE
vizkit/typelib_qt_adapter.rb:200: [BUG] Segmentation fault at 0x00000000000000 ruby 2.3.1p112

### ISSUE THREAD

**Issue by chyphen777** [ruby/b.r-l.o#99]
Trying to run a rb script, (url
[sonar_multibeam-run.rb.txt](https://github.com/ruby/b.r-l.o/files/3019735/sonar_multibeam-run.rb.txt) with ruby-2.3.1 and got errors message (url
[sonar_multibeam.rb.bugs.txt](https://github.com/ruby/b.r-l.o/files/3019737/sonar_multibeam.rb.bugs.txt), excerpted below.  (A note at the end of the message suggested that I may have encountered a bug i the Ruby interpreter or extension libraries)

...
Vizkit[WARN]: deprecation: use Async API to connect the port /sonar_multibeam.sonar_samples to a widget or code block
orocos.rb[WARN]: TaskContextProxy /sonar_multibeam is already initialized with different options.
/home/cchien/sonar_simulation/gui/vizkit
[sonar_multibeam-run.rb.txt](https://github.com/ruby/b.r-l.o/files/3019732/sonar_multibeam-run.rb.txt)
/lib/vizkit/typelib_qt_adapter.rb:200: [BUG] Segmentation fault at 0x00000000000000
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
...

Any suggestion for tracking down or fixing the issue are appreciated.   Thanks.
C. Chien

**Comment by hsbt** [comment]
This repository is not the language tracker. Please file it to https://bugs.ruby-lang.org/projects/ruby-trunk/issues.
